spring:
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
      profile: dev
  application:
    name: config-client
server:
  port: 8989
eureka:
  instance:
    hostname: config-client
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
