spring:
  application:
    name: service-feign
server:
    port: 8764
eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

feign:
    hystrix:
      enabled: true