spring:
  application:
    name: service-ribbon
server:
    port: 8765

eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

